version: '3.8'

services:
  db:
    image: mysql:5.7
    profiles: [ "db" ]
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - concrete-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    profiles: ["db"]
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - concrete-network
  concrete:
    image: paulcharpie/concrete-cms:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    ports:
      - "8081:80"
    volumes:
      - ${SITE_FILES_PATH}:/var/www/html/application/files
      - ${PACKAGES_PATH}:/var/www/html/packages
    networks:
      - concrete-network
volumes:
  mysql_data:
networks:
  concrete-network:
    external: true